# Netlify configuration file for Map-on-Solana
# Clean static export build for Next.js 14.x

[build]
  command = "npm run build"
  publish = "out"
  base = "/"

[build.environment]
  NODE_VERSION = "22.21.0"
  NEXT_TELEMETRY_DISABLED = "1"
  NETLIFY_NEXT_PLUGIN_SKIP = "true"  # 👈 This line disables the Netlify Next.js plugin

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  included_files = ["app/api/**"]
